import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { Patient } from "../../types/appwrite.types";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const parseStringify = (value: any) => JSON.parse(JSON.stringify(value));

export const convertFileToUrl = (file: File) => URL.createObjectURL(file);

// FORMAT DATE TIME
export const formatDateTime = (
  dateString: Date | string,
  timeZone: string = Intl.DateTimeFormat().resolvedOptions().timeZone,
) => {
  const dateTimeOptions: Intl.DateTimeFormatOptions = {
    // weekday: "short", // abbreviated weekday name (e.g., 'Mon')
    month: "short", // abbreviated month name (e.g., 'Oct')
    day: "numeric", // numeric day of the month (e.g., '25')
    year: "numeric", // numeric year (e.g., '2023')
    hour: "numeric", // numeric hour (e.g., '8')
    minute: "numeric", // numeric minute (e.g., '30')
    hour12: true, // use 12-hour clock (true) or 24-hour clock (false),
    timeZone: timeZone, // use the provided timezone
  };

  const dateDayOptions: Intl.DateTimeFormatOptions = {
    weekday: "short", // abbreviated weekday name (e.g., 'Mon')
    year: "numeric", // numeric year (e.g., '2023')
    month: "2-digit", // abbreviated month name (e.g., 'Oct')
    day: "2-digit", // numeric day of the month (e.g., '25')
    timeZone: timeZone, // use the provided timezone
  };

  const dateOptions: Intl.DateTimeFormatOptions = {
    month: "short", // abbreviated month name (e.g., 'Oct')
    year: "numeric", // numeric year (e.g., '2023')
    day: "numeric", // numeric day of the month (e.g., '25')
    timeZone: timeZone, // use the provided timezone
  };

  const timeOptions: Intl.DateTimeFormatOptions = {
    hour: "numeric", // numeric hour (e.g., '8')
    minute: "numeric", // numeric minute (e.g., '30')
    hour12: true, // use 12-hour clock (true) or 24-hour clock (false)
    timeZone: timeZone, // use the provided timezone
  };

  const formattedDateTime: string = new Date(dateString).toLocaleString(
    "en-US",
    dateTimeOptions,
  );

  const formattedDateDay: string = new Date(dateString).toLocaleString(
    "en-US",
    dateDayOptions,
  );

  const formattedDate: string = new Date(dateString).toLocaleString(
    "en-US",
    dateOptions,
  );

  const formattedTime: string = new Date(dateString).toLocaleString(
    "en-US",
    timeOptions,
  );

  return {
    dateTime: formattedDateTime,
    dateDay: formattedDateDay,
    dateOnly: formattedDate,
    timeOnly: formattedTime,
  };
};

export function encryptKey(passkey: string) {
  return btoa(passkey);
}

export function decryptKey(passkey: string) {
  return atob(passkey);
}

export function parseCookieHeader(cookieHeader: string) {
  return cookieHeader
    .split(";")
    .map((c) => c.trim())
    .reduce<Record<string, string>>((acc, c) => {
      const [key, ...v] = c.split("=");
      if (!key) return acc;
      acc[key] = decodeURIComponent(v.join("="));
      return acc;
    }, {});
}

export const downloadPatientData = (
  patientId: string,
  patientData: Patient,
): Promise<{ success: boolean }> => {
  return new Promise((resolve, reject) => {
    try {
      const docContent = `
DOCSYNC MEDICAL RECORDS
=======================

Date Generated: ${new Date().toLocaleDateString()}
Generated For: ${patientData.name}

PERSONAL INFORMATION
-------------------
Full Name: ${patientData.name}
Email: ${patientData.email}
Phone: ${patientData.phone}
Date of Birth: ${new Date(patientData.birthDate).toLocaleDateString()}
Gender: ${patientData.gender}
Address: ${patientData.address}
Occupation: ${patientData.occupation}

EMERGENCY CONTACT
-----------------
Contact Name: ${patientData.emergencyContactName}
Contact Number: ${patientData.emergencyContactNumber}

MEDICAL INFORMATION
------------------
Primary Physician: ${patientData.primaryPhysician}
Insurance Provider: ${patientData.insuranceProvider}
Policy Number: ${patientData.insurancePolicyNumber}
Allergies: ${patientData.allergies || "None"}
Current Medications: ${patientData.currentMedication || "None"}
Family Medical History: ${patientData.familyMedicalHistory || "None"}
Past Medical History: ${patientData.pastMedicalHistory || "None"}

IDENTIFICATION
--------------
ID Type: ${patientData.identificationType || "N/A"}
ID Number: ${patientData.identificationNumber || "N/A"}

CONSENT
-------
Treatment Consent: ${patientData.treatmentConsent ? "Granted" : "Not Granted"}
Disclosure Consent: ${patientData.disclosureConsent ? "Granted" : "Not Granted"}
Privacy Consent: ${patientData.privacyConsent ? "Granted" : "Not Granted"}

--------------------------------------------------
Generated by DocSync
© ${new Date().getFullYear()} DocSync
`;

      const blob = new Blob([docContent], {
        type: "text/plain;charset=utf-8",
      });

      const downloadUrl = URL.createObjectURL(blob);

      const link = document.createElement("a");

      link.href = downloadUrl;

      link.download = `DocSync_Medical_Record_${patientData.name.replace(
        /\s+/g,
        "_",
      )}.txt`;

      link.style.display = "none";

      document.body.appendChild(link);

      link.click();

      document.body.removeChild(link);

      URL.revokeObjectURL(downloadUrl);

      // allow browser a tiny moment
      setTimeout(() => {
        resolve({ success: true });
      }, 300);
    } catch (error) {
      reject(error);
    }
  });
};
