"use server";

import { ID, Query } from "node-appwrite";

import { createSessionClient } from "../appwrite/server";
import { ActionResult, handleError } from "../errors";
import { parseStringify } from "../utils";
import { Patient } from "../../../types/appwrite.types";

// REGISTER PATIENT
export const registerPatient = async ({
  identificationDocument,
  ...patient
}: RegisterUserParams): Promise<ActionResult<PatientData>> => {
  try {
    const { tablesDB, permissions } = await createSessionClient();

    const fileId = identificationDocument?.get("fileId") as string;
    const fileUrl = identificationDocument?.get("fileUrl") as string;

    const newPatient = await tablesDB.createRow({
      databaseId: process.env.DATABASE_ID!,
      tableId: process.env.PATIENT_TABLE_ID!,
      rowId: ID.unique(),
      data: {
        identificationDocumentId: fileId ?? null,
        identificationDocumentUrl: fileUrl ?? null,
        ...patient,
      },
      permissions: [permissions],
    });

    return {
      success: true,
      data: { patient: parseStringify(newPatient) },
    };
  } catch (error) {
    console.error("Error creating patient personal info:", error);
    return handleError(error);
  }
};

// GET PATIENT
export const getPatient = async (
  userId: string,
): Promise<ActionResult<PatientData>> => {
  try {
    const { tablesDB } = await createSessionClient();

    const patient = await tablesDB.listRows({
      databaseId: process.env.DATABASE_ID!,
      tableId: process.env.PATIENT_TABLE_ID!,
      queries: [Query.equal("userId", [userId])],
    });

    return {
      success: true,
      data: { patient: parseStringify(patient.rows[0] || null) },
    };
  } catch (error) {
    console.error("Error fetching patient:", error);
    return handleError(error);
  }
};

// Update patient profile
export const updatePatient = async (
  patientId: string,
  data: Partial<Patient>,
): Promise<ActionResult<PatientData>> => {
  try {
    const { tablesDB, permissions } = await createSessionClient();

    const updatedPatient = await tablesDB.updateRow({
      databaseId: process.env.DATABASE_ID!,
      tableId: process.env.PATIENT_TABLE_ID!,
      rowId: patientId,
      data,
    });

    return {
      success: true,
      data: { patient: parseStringify(updatedPatient) },
    };
  } catch (error) {
    return handleError(error);
  }
};

export const getAllPatients = async (): Promise<
  ActionResult<{ patients: Patient[] }>
> => {
  try {
    const { tablesDB } = await createSessionClient();
    const patients = await tablesDB.listRows({
      databaseId: process.env.DATABASE_ID!,
      tableId: process.env.PATIENT_TABLE_ID!,
      queries: [Query.limit(100)],
    });
    return {
      success: true,
      data: { patients: parseStringify(patients.rows) },
    };
  } catch (error) {
    return handleError(error);
  }
};

// Download patient data as PDF
export const downloadPatientData = async (
  patientId: string,
  patientData: any,
) => {
  try {
    // Generate a well-structured document
    const docContent = `
DOCSYNC MEDICAL RECORDS
=======================
Date Generated: ${new Date().toLocaleDateString()}
Generated for: ${patientData.name}

PERSONAL INFORMATION
-------------------
Full Name: ${patientData.name}
Email: ${patientData.email}
Phone: ${patientData.phone}
Date of Birth: ${new Date(patientData.birthDate).toLocaleDateString()}
Gender: ${patientData.gender}
Address: ${patientData.address}
Occupation: ${patientData.occupation}

EMERGENCY CONTACT
-----------------
Contact Name: ${patientData.emergencyContactName}
Contact Number: ${patientData.emergencyContactNumber}

MEDICAL INFORMATION
------------------
Primary Physician: ${patientData.primaryPhysician}
Insurance Provider: ${patientData.insuranceProvider}
Policy Number: ${patientData.insurancePolicyNumber}
Allergies: ${patientData.allergies || "None"}
Current Medications: ${patientData.currentMedication || "None"}
Family Medical History: ${patientData.familyMedicalHistory || "None"}
Past Medical History: ${patientData.pastMedicalHistory || "None"}

IDENTIFICATION
--------------
ID Type: ${patientData.identificationType || "N/A"}
ID Number: ${patientData.identificationNumber || "N/A"}

CONSENT
-------
Treatment Consent: ${patientData.treatmentConsent ? "Granted" : "Not Granted"}
Disclosure Consent: ${patientData.disclosureConsent ? "Granted" : "Not Granted"}
Privacy Consent: ${patientData.privacyConsent ? "Granted" : "Not Granted"}

---
This document is electronically generated by DocSync.
For questions, contact support@docsync.com
© ${new Date().getFullYear()} DocSync. All rights reserved.
    `;

    // Create and download as text file (you can enhance this with jsPDF for actual PDF)
    const blob = new Blob([docContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `DocSync_Medical_Records_${patientData.name.replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    return { success: true };
  } catch (error) {
    return handleError(error);
  }
};
