export enum ErrorCode {
  // Generic
  UNKNOWN = "UNKNOWN",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // Auth
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_ALREADY_AUTHENTICATED = "AUTH_ALREADY_AUTHENTICATED",
  AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",

  // Resource
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",

  // Network
  NETWORK_ERROR = "NETWORK_ERROR",
  NETWORK_TIMEOUT = "NETWORK_TIMEOUT",

  // Rate limit
  RATE_LIMITED = "RATE_LIMITED",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",

  // File
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  FILE_INVALID_TYPE = "FILE_INVALID_TYPE",
  FILE_DELETE_FAILED = "FILE_DELETE_FAILED",

  // Business logic
  PATIENT_ALREADY_EXISTS = "PATIENT_ALREADY_EXISTS",
  APPOINTMENT_CONFLICT = "APPOINTMENT_CONFLICT",
  APPOINTMENT_NOT_AVAILABLE = "APPOINTMENT_NOT_AVAILABLE",

  // Email
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
  EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED",
}
